// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpPhrzQQvH-iIrYoiH4Jfy7jrvFxc_NTE',
    appId: '1:759442523095:web:d76324fddf66df2f4ec192',
    messagingSenderId: '759442523095',
    projectId: 'actors-app-138d6',
    authDomain: 'actors-app-138d6.firebaseapp.com',
    storageBucket: 'actors-app-138d6.firebasestorage.app',
    measurementId: 'G-QZQ6QWE1DL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbgDKW4m7mtLaMOXrv9gZUbPUtqsRWkfc',
    appId: '1:759442523095:android:1ef757e9fa6b4ce74ec192',
    messagingSenderId: '759442523095',
    projectId: 'actors-app-138d6',
    storageBucket: 'actors-app-138d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh61cc4RznrSD2494aa8ir5pWE6kV9t4E',
    appId: '1:759442523095:ios:c148bfe6c84a2cca4ec192',
    messagingSenderId: '759442523095',
    projectId: 'actors-app-138d6',
    storageBucket: 'actors-app-138d6.firebasestorage.app',
    iosBundleId: 'com.example.actorsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh61cc4RznrSD2494aa8ir5pWE6kV9t4E',
    appId: '1:759442523095:ios:c148bfe6c84a2cca4ec192',
    messagingSenderId: '759442523095',
    projectId: 'actors-app-138d6',
    storageBucket: 'actors-app-138d6.firebasestorage.app',
    iosBundleId: 'com.example.actorsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpPhrzQQvH-iIrYoiH4Jfy7jrvFxc_NTE',
    appId: '1:759442523095:web:5e273504f78f06ca4ec192',
    messagingSenderId: '759442523095',
    projectId: 'actors-app-138d6',
    authDomain: 'actors-app-138d6.firebaseapp.com',
    storageBucket: 'actors-app-138d6.firebasestorage.app',
    measurementId: 'G-QH5YV1MKPB',
  );
}
